                                                    (c) Raju Pandey, Thinking Books, LLC. 2020.

# Numpy  Programming Project
## Introduction
In this project, you will implement several functions using Numpy. Please implement the solutions in the cells shown below. (Please do not change the names of the functions.)

### Add Import Definitions Below 

### Problem 1 (10 pts). Array Creation
Write a function, 'create_array', that takes three parameters:

* m: number of rows
* n: number of columns
* values: a list of tuples (e.g., [(1, 3), (4, 8), (3, 9)])

'create_array' returns a numpy array of shape (m, n). Each ith row of this array contains value computed in the following manner:
* find the ith tuple from 'values' parameter, say tuple_i
* start = tuple_i[0], stop = tuple_i[1]
* The ith row contains 'n' (number of columns) evenly spaced numbers between 'start' and 'stop'.

#### Example Usage
    ```
    arr = create_array(3, 3, [(1, 3), (3, 5), (4, 8)])
    print('**** df ****')
    print(arr)
    **** df ****
    [[1 2 3]
     [3 4 5]
     [4 6 8]]
     ```

In [65]:
def create_array(m, n, values):
    arr = np.full((m, n), 0)
    ## Add your code below 

    
    return arr

### Problem 2 (10 pts).  Reshaping Array
Write a function, 'rotate_array', that takes three parameters:

* array: a numpy 1-D or 2-D array, 
* shift_right_by: an integer, and
* target_shape: a tuple - either 1D or 2D

'rotate_array' will first flatten the  'array' into a 1-D array. It will then shift the flattened array to the right by 'shift_right_by' amount. Finally, the function will reshape the shifted array into the shape specified by 'target_shape'.

#### Example Usage
    ```
    arr = rotate_array(np.array([1, 2, 3, 4]), 1, (2,2))
    print(arr)
    [[4 1]
    [2 3]]
    arr = rotate_array(np.array([1, 2, 3, 4, 5, 6]), 2, (2,3))
    print(arr)
    [[5 6 1]
    [2 3 4]]
    ````

In [1]:
def rotate_array(array, shift_right_by, target_shape):
        ## array to be reshaped
        ## shift_right_by: integer
        ## target_shape: tuple describing the shape of the target array. Can be (m, ) or (m, n)
    new_array = None  ## RETURN new_array
    ## Add your code below 
    
    
    return new_array


### Problem 3 (5 pts). Splitting Array Horizontally
Assume that all arrays are 2-dimensional for this problem. Write a function, split_horizontally, that takes two parameters: 

* array: a 2-D numpy array
* numCols: integer

'split_horizontally' will return two arrays. The first array will contain the 'numCol' columns of 'array' and the second array will contain the rest of the columns.

####  Example Usage
    `
        a = np.array([[1, 2, 3], [4, 5, 6]])
        arr1, arr2 = split_horizontally(a, 1)
        print(****arr1****)
        print(arr1)
        print(****arr2****)
        print(arr2)

        ****arr1****
        array([[1], [4]])
        ****arr2****
        array([[2, 3], [5, 6]]))
    `

In [37]:
def split_horizontally(array, numCols):
    ## Add your code below 

    
    
    return arr1, arr2

### Problem 4 (5 pts). Splitting Array Vertically
Assume that all arrays are 2-dimensional for this problem. Write a function, split_vertically, that takes two parameters: 

* array: a 2-D numpy array
* numRows: integer

'split_vertically' will return two arrays. The first array will contain the 'numRows' rows of 'array' and the second array will contain the rest of the rows.

####  Example Usage
    `
        a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
        arr1, arr2 = split_vertically(a, 1)
        print(****arr1****)
        print(arr1)
        print(****arr2****)
        print(arr2)

        ****arr1****
        array([[1, 2, 3], [4, 5, 6]])
        ****arr2****
        array([[7, 8, 9]])
     `

In [44]:
def split_vertically(array, numRows):
    ## Add your code below 

    
    
    return arr1, arr2

### Problem 5 (5 pts). Splitting and Merge Array Horizontally
Assume that all arrays are 2-dimensional for this problem. Write a function, split_and_merge_horizontally, that takes 4 parameters: 

* array1, array2: 2-D numpy arrays, with the same number of rows.
* numCol1, numCol2: integers

'split_and_merge_horizontally' will first split 'array1' into two arrays: 'arr11' and 'arr12'. 'arr11' will contain the first 'numCol1' columns and 'arr12' the rest. Similarly, it splits 'array2' into two arrays:  'arr21' and 'arr22'. 'arr21' will contain the first 'numCol2' columns, and 'arr22' the rest. The function will then create two arrays: (i) a horizontally stack of 'arr11' with 'arr22', and (ii) a horizontal stack of 'arr21' with 'arr12'. The function will return the two arrays.

####  Example Usage
    `
        a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
        b = a+100
        arr1, arr2 = split_and_merge_horizontally(a, b, 2, 2)
        print(****arr1****)
        print(arr1)
        print(****arr2****)
        print(arr2)

        ****arr1****
        array([[  1,   2, 103],
               [  4,   5, 106],
               [  7,   8, 109]])
        ****arr2****
        array([[101, 102,   3],
               [104, 105,   6],
               [107, 108,   9]])
    `

In [50]:
def split_and_merge_horizontally(array1, array2, numCol1, numCol2):
    ## Add your code below 
    
    
    return arr1, arr2

### Problem 6 (5 pts). Splitting and Merge Array Vertically
Assume that all arrays are 2-dimensional. Write a function, split_and_merge_vertically, that takes 4 parameters: 

* array1, array2: 2-D numpy arrays, with the same number of columns.
* numRow1, numRow2: integers

'split_and_merge_vertically' will first split 'array1' into two arrays: 'arr11' and 'arr12'. 'arr11' will contain the first 'numRow1' rows and 'arr12' the rest. Similary it splits 'array2' into two arrays:  'arr21' and 'arr22'. 'arr21' will contain the first 'numRow2' rows, and 'arr22' the rest. The function will then create two arrays: (i) a vertical stack of 'arr11' with 'arr22', and (ii) a vertical stack of 'arr21' with 'arr12'. The function will return the two arrays.

####  Example Usage
    `
        a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
        b = a+100
        arr1, arr2 = split_and_merge_vertically(a, b, 2, 2)
        print(****arr1****)
        print(arr1)
        print(****arr2****)
        print(arr2)

        ****arr1****
        array([[  1,     2,   3],
               [  4,     5,   6],
               [  107,   108, 109]])
        ****arr2****
        array([[101, 102,   103],
               [104, 105,   106],
               [7,   8,   9]])
    `               

In [55]:
def split_and_merge_vertically(array1, array2, numRow1, numRow2):
    ## Add your code below 

    
    return arr1, arr2

### Problem 7 (15 pts). Array Operations
Write a function, 'evaluate', that takes two parameters:

* operands: a list that can contain any number of numpy arrays, integer and/or floats.
* operators: a list of strings that may include '+', '-', '*', '/', 'log', and/or'sqrt'.
The function operates as follows: 
* The function will begin by popping off the first operand from the 'operands' list into 'result'
* It will then pop off the next operator from 'operators' list.
* If the operator is log' or 'sqrt', it will apply np.log or np.sqrt on the current result.
* If the operator is '+', '-', '*' or '/', 
    * it will first pop off the next operand from the 'operands' list
    * it will apply the corresponding binary numpy array-array or scalar-array operator on the result and the popped off operand
* The function will continue to evaluate the operators on the operands until the 'operators' list is empty. After it has exhausted all operators, the array will return the result.  

Consider the example where the operands list is [a, 2] and operator list is ['+', 'sqrt']. The function will first evaluate a+2 using the '+' operator on operands a and 2. It will then apply 'numpy.sqrt' on the result a+2, returning numpy.sqrt(a+2). Similarly, the result of evaluate([a, 2, b, 3], ['*', '+', 'sqrt', '-']) is equivalent to numpy.sqrt(a*2)+b)-3. Here a and b can both be numpy arrays.

####  Example Usage
    `
        a = np.array([1, 2, 3])
        b = np.array([2, 4, 6])
        result = evaluate([a, 2, b, 3], ['*', '+', 'sqrt', '-'])
        print(result)
        array([-1.        , -0.17157288,  0.46410162])
    `

In [62]:
def evaluate(operands, operators):
    result = None
    #### Add your code here ####
    
    
    
    return result